# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
:stages:
- build
- deploy
:variables:
  :NODE_ENV: development
  :APP_NAME: zigbee2mqtt-ui
  :DEPLOY_PATH: "devserver/zigbee"

:build:
  :stage: build
  :image: node:20
  :script:
  - npm install
  - npm audit
  - npm run build
  :artifacts:
    :paths:
    - dist/zigbee2mqtt-ui/browser
    :expire_in: 1 day

:deploy:
  :stage: deploy
  :image: alpine:latest
  :dependencies:
  - build
  :script:
      - apk add --no-cache samba-client
      # Debug: List available shares
      - smbclient -L //$SMB_HOST -U $SMB_USER%$SMB_PASSWORD
      # Debug: Try to connect and list directory
      - smbclient //$SMB_HOST/$SMB_SHARE -U $SMB_USER%$SMB_PASSWORD -c "ls"
      # Copy files
      - smbclient //$SMB_HOST/$SMB_SHARE -U $SMB_USER%$SMB_PASSWORD -c "cd $DEPLOY_PATH; prompt OFF; recurse ON; mput dist/zigbee2mqtt-ui/browser/*"

  :only:
    - master
  

