# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/user/application_security/secret_detection/pipeline/configure
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
:stages:
- build
- test
- deploy

:variables:
  :NODE_ENV: development
  :APP_NAME: zigbee2mqtt-ui
  :DEPLOY_PATH: "data/devserver/zigbee"


:build:
  :stage: build
  :image: node:20
  :script:
  - npm install --legacy-peer-deps
  - npm audit

  - npm run build
  :artifacts:
    :paths:
    - dist
    :expire_in: 1 day
include:
  - template: Jobs/SAST.gitlab-ci.yml

:test:
  :stage: test
  :image: node:20
  :script:
  - npm run test


# If you need to customize, ensure the artifact is properly declared
sast:
  artifacts:
    reports:
      sast: gl-sast-report.json
    paths:
      - gl-sast-report.json
    expire_in: 1 week

:deploy:
  :stage: deploy
  :image: alpine:latest
  :dependencies:
  - build
  :script:
      - apk add --no-cache samba-client
      - |
        # Build command script with all mkdir and put commands
        {
          echo "cd $DEPLOY_PATH"
          # Create all directories first (in order of depth)
          find dist/ -type d ! -name browser | sed 's|dist/||' | sed '/^$/d' | sort | while read dir; do
            echo "mkdir $dir"
          done
          # Upload all files
          find dist/ -type f | while read file; do
            relpath="${file#dist/}"
            echo "put $file $relpath"
          done
          echo "quit"
        } | smbclient //$SMB_HOST/$SMB_SHARE -U $SMB_USER%$SMB_PASSWORD 2>&1 | grep -v "Try \"help\""
  :only:
    - master
  

